.TH OPEN_MNLINK 1 2025-May "" "open_mnlink"
.SH NAME
open_mnlink \- open_mnlink(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'127.0.0.1'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)
.SH SYNOPSIS
\fIopen_mnlink(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'127.0.0.1'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)\fR
.SH OPTIONS
.PP
\fBuser\fB \fR\- . 
.PP
.PP
\fBpasswd\fB \fR\- . 
.PP
.PP
\fBhost\fB \fR\- '127.0.0.1'. 
.PP
.PP
\fBport\fB \fR\- 3306. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_mnlink at mn_tools.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
