.\" man page create by R# package system.
.TH MSIMAGING 1 2000-Jan "HEstain_tissue_reader" "HEstain_tissue_reader"
.SH NAME
HEstain_tissue_reader \- image processor for huge HE-stain bitmap file
.SH SYNOPSIS
\fIHEstain_tissue_reader(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
image processor for huge HE-stain bitmap file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 the file path to the HE-stain image file, should be processed as bitmap 
 file at first via image processing software like photoshop.
. 
.PP
.SH SEE ALSO
MsImaging
.SH FILES
.PP
hpc.dll
.PP
