.\" man page create by R# package system.
.TH MSIMAGING 1 2000-Jan "MSI_ionStat_parallel" "MSI_ionStat_parallel"
.SH NAME
MSI_ionStat_parallel \- run measure of the ion features in IPC parallel for a huge ms-imaging rawdata matrix
.SH SYNOPSIS
\fIMSI_ionStat_parallel(\fBx\fR as <generic> MzMatrix, 
\fBgrid_size\fR as integer = 5);\fR
.SH DESCRIPTION
.PP
run measure of the ion features in IPC parallel for a huge ms-imaging rawdata matrix
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBgrid_size\fB \fR\- -. 
.PP
.SH SEE ALSO
MsImaging
.SH FILES
.PP
hpc.dll
.PP
