.\" man page create by R# package system.
.TH MSIMAGING 1 2000-Jan "SCMs_ionStat_parallel" "SCMs_ionStat_parallel"
.SH NAME
SCMs_ionStat_parallel \- run measure of the ion features in IPC parallel
.SH SYNOPSIS
\fISCMs_ionStat_parallel(\fBx\fR as <generic> MzMatrix);\fR
.SH DESCRIPTION
.PP
run measure of the ion features in IPC parallel
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
MsImaging
.SH FILES
.PP
hpc.dll
.PP
