.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "cluster_spectrum" "cluster_spectrum"
.SH NAME
cluster_spectrum \- 
.SH SYNOPSIS
\fIcluster_spectrum(\fBrepo\fR as <generic> dataPool, 
\fBcluster_id\fR as string);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
