.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "consensus_model" "consensus_model"
.SH NAME
consensus_model \- 
.SH SYNOPSIS
\fIconsensus_model(\fBrepo\fR as <generic> dataPool, 
\fBmodel_id\fR as string, 
\fBdims\fR as integer = 9, 
\fBknn\fR as integer = 64, 
\fBcutoff\fR as double = 0.8);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
