.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "consensus_annotation" "consensus_annotation"
.SH NAME
consensus_annotation \- 
.SH SYNOPSIS
\fIconsensus_annotation(\fBrepo\fR as <generic> dataPool, 
\fBmodel\fR as <generic> consensus_model, 
\fBcluster_id\fR as string);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
