.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "createMysqlPool" "createMysqlPool"
.SH NAME
createMysqlPool \- create a new spectrum clustering data pool
.SH SYNOPSIS
\fIcreateMysqlPool(\fBrepo\fR as <generic> dataPool, 
\fBlevel\fR as double = 0.9, 
\fBsplit\fR as integer = 9, 
\fBname\fR as string = "no_named", 
\fBdesc\fR as string = "no_information");\fR
.SH DESCRIPTION
.PP
create a new spectrum clustering data pool
.PP
.SH OPTIONS
.PP
\fBlevel\fB \fR\- -. 
.PP
.PP
\fBsplit\fB \fR\- hex, max=15. 
.PP
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
