.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "file_info" "file_info"
.SH NAME
file_info \- 
.SH SYNOPSIS
\fIfile_info(\fBrepo\fR as <generic> dataPool, 
\fBfilepath\fR as string, 
\fBgroup\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
