.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "group_info" "group_info"
.SH NAME
group_info \- 
.SH SYNOPSIS
\fIgroup_info(\fBrepo\fR as <generic> dataPool, 
\fBgroup\fR as string, 
\fBorganism\fR as string = "Unknown", 
\fBbio_sample\fR as string = "Unknown", 
\fBrepo_dir\fR as string = "");\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
