.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "project_context" "project_context"
.SH NAME
project_context \- 
.SH SYNOPSIS
\fIproject_context(\fBrepo\fR as <generic> dataPool, 
\fBproject_id\fR as string, 
\fBname\fR as string = \fB<NULL>\fR, 
\fBdesc\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
