.\" man page create by R# package system.
.TH MOLECULE_NETWORKING 1 2000-Jan "scan_consensus" "scan_consensus"
.SH NAME
scan_consensus \- 
.SH SYNOPSIS
\fIscan_consensus(\fBmysql\fR as <generic> dataPool, 
\fBargs\fR as <generic> consensus_model, 
\fBpage_size\fR as integer = 1000, 
\fBtop\fR as integer = 30);\fR
.SH SEE ALSO
molecule_networking
.SH FILES
.PP
hpc.dll
.PP
