.\" man page create by R# package system.
.TH DECONVOLUTION 1 2000-Jan "peak_alignments" "peak_alignments"
.SH NAME
peak_alignments \- Make peak group alignments and export peaktable
.SH SYNOPSIS
\fIpeak_alignments(\fBpeak_groups\fR as <generic> XICPool, 
\fBfeatures_mz\fR as double, 
\fBtolerance\fR as any = "da:0.005", 
\fBpeak_width\fR as any = "3,15", 
\fBbaseline\fR as double = 0.65, 
\fBjoint\fR as boolean = FALSE, 
\fBdtw\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Make peak group alignments and export peaktable
.PP
.SH OPTIONS
.PP
\fBpeak_groups\fB \fR\- -. 
.PP
.PP
\fBfeatures_mz\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function returns a vector of the @\fBT:BioNovoGene.Analytical.MassSpectrometry.Math.xcms2\fR peaks data, andalso 
 the @\fBT:BioNovoGene.Analytical.MassSpectrometry.Math.RtShift\fR value is attached in the value vector via R# object
 attribute named \fBrt.shift\fR.
.PP
.SH SEE ALSO
deconvolution
.SH FILES
.PP
hpc.dll
.PP
