.\" man page create by R# package system.
.TH MOLECULE_TREE 1 2000-Jan "add_molecule" "add_molecule"
.SH NAME
add_molecule \- add molecule model data into database pool
.SH SYNOPSIS
\fIadd_molecule(\fBtree\fR as <generic> molecule_tree, 
\fBmeta\fR as <generic> MetaboliteAnnotation, 
\fBsmiles\fR as any);\fR
.SH DESCRIPTION
.PP
add molecule model data into database pool
.PP
.SH OPTIONS
.PP
\fBtree\fB \fR\- -. 
.PP
.PP
\fBmeta\fB \fR\- the brief metabolite annotation information for make cache. 
.PP
.PP
\fBsmiles\fB \fR\- molecule structure data. 
.PP
.SH SEE ALSO
molecule_tree
.SH FILES
.PP
hpc.dll
.PP
