.\" man page create by R# package system.
.TH MOLECULE_TREE 1 2000-Jan "fetch_tree" "fetch_tree"
.SH NAME
fetch_tree \- Download the molecule tree graph from the database
.SH SYNOPSIS
\fIfetch_tree(\fBtree\fR as <generic> molecule_tree, 
\fBmodel\fR as string);\fR
.SH DESCRIPTION
.PP
Download the molecule tree graph from the database
.PP
.SH OPTIONS
.PP
\fBtree\fB \fR\- -. 
.PP
.PP
\fBmodel\fB \fR\- -. 
.PP
.SH SEE ALSO
molecule_tree
.SH FILES
.PP
hpc.dll
.PP
