.\" man page create by R# package system.
.TH MOLECULE_TREE 1 2000-Jan "fetch_matrix" "fetch_matrix"
.SH NAME
fetch_matrix \- 
.SH SYNOPSIS
\fIfetch_matrix(\fBtree\fR as <generic> molecule_tree, 
\fBdb_xrefs\fR as any, 
\fBprefix\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
molecule_tree
.SH FILES
.PP
hpc.dll
.PP
