.\" man page create by R# package system.
.TH MOLECULE_TREE 1 2000-Jan "make_clusterTree" "make_clusterTree"
.SH NAME
make_clusterTree \- 
.SH SYNOPSIS
\fImake_clusterTree(\fBtree\fR as <generic> molecule_tree, 
\fBmodel\fR as string, 
\fBcluster_cutoff\fR as <generic> Double = \fB<NULL>\fR, 
\fBright_cutoff\fR as <generic> Double = \fB<NULL>\fR);\fR
.SH SEE ALSO
molecule_tree
.SH FILES
.PP
hpc.dll
.PP
