.\" man page create by R# package system.
.TH MOLECULE_TREE 1 2000-Jan "molecule_set" "molecule_set"
.SH NAME
molecule_set \- get a set of the molecule information in a given model
.SH SYNOPSIS
\fImolecule_set(\fBtree\fR as <generic> molecule_tree, 
\fBmodel\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get a set of the molecule information in a given model
.PP
.SH OPTIONS
.PP
\fBtree\fB \fR\- -. 
.PP
.PP
\fBmodel\fB \fR\- 
 the name reference to a specific model
. 
.PP
.SH SEE ALSO
molecule_tree
.SH FILES
.PP
hpc.dll
.PP
