-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 14:41:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema molecule_tree
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `molecule_tree` ;

-- -----------------------------------------------------
-- Schema molecule_tree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `molecule_tree` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `molecule_tree` ;

-- -----------------------------------------------------
-- Table `atoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atoms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `atoms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'the unique reference id of current atom group, in integer id representative',
  `unique_id` VARCHAR(64) NOT NULL COMMENT 'the unique reference id of current atom group, in character representative',
  `atom_group` VARCHAR(45) NOT NULL COMMENT 'the atom group name, could be duplicated',
  `element` VARCHAR(8) NOT NULL COMMENT 'the base element atom of current group data',
  `aromatic` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'on an aromatic ring? 1 means true',
  `hydrogen` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'The number of the hydrogen of current atom group it has',
  `charge` INT NOT NULL DEFAULT 0 COMMENT 'the ion charge value of current atom group, could be a positive/negative integer value',
  `add_time` DATETIME NOT NULL DEFAULT now() COMMENT 'create time of this atom group',
  `note` LONGTEXT NULL COMMENT 'description about this atom group data',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'atom group information data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `atoms` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_id_UNIQUE` ON `atoms` (`unique_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `graph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graph` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `graph` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `molecule_id` INT UNSIGNED NOT NULL COMMENT 'the unique reference id of the molecule from external database records',
  `graph` JSON NOT NULL COMMENT 'network graph model',
  `matrix` LONGTEXT NOT NULL COMMENT 'matrix representive of the graph json, base64 encoded double[] matrix data',
  `add_time` DATETIME NOT NULL DEFAULT now() COMMENT 'create time of current molecule graph model',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'the molecule structure graph';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `graph` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `molecule_atoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molecule_atoms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `molecule_atoms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `molecule` INT UNSIGNED NOT NULL,
  `atom_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'relationship between a molecule and atom groups';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `molecule_atoms` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `molecules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molecules` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `molecules` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `db_xref` VARCHAR(255) NOT NULL,
  `name` VARCHAR(2048) NOT NULL,
  `formula` VARCHAR(64) NOT NULL,
  `exact_mass` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `smiles` LONGTEXT NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'cache pool of external molecule data set';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `molecules` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tree` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tree` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id of the edge',
  `parent_id` INT UNSIGNED NOT NULL COMMENT '[id] of the parent node of current node',
  `graph_id` INT UNSIGNED NOT NULL COMMENT 'the molecule structure graph reference id of current node',
  `cosine` DOUBLE UNSIGNED NOT NULL DEFAULT 0 COMMENT 'cosine similarity of current node when compares with the parent node',
  `add_time` DATETIME NOT NULL DEFAULT now() COMMENT 'create time of current cluster node',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'the cluster tree network data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `tree` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `graph_data_index` ON `tree` (`graph_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
