-- MySQL Script generated by MySQL Workbench
-- Wed May 28 14:55:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sample_pool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sample_pool` ;

-- -----------------------------------------------------
-- Schema sample_pool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample_pool` DEFAULT CHARACTER SET utf8mb3 ;
SHOW WARNINGS;
USE `sample_pool` ;

-- -----------------------------------------------------
-- Table `cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cluster` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cluster` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` INT UNSIGNED NOT NULL COMMENT 'the graph model reference id',
  `key` VARCHAR(64) NOT NULL COMMENT 'the key name of current cluster tree node',
  `parent_id` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'default value 0 means current tree node is root node',
  `n_childs` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'the number of childs that contains in current cluster tree node',
  `n_spectrum` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'the cluster size: number of the spectrum data that inside this cluster data',
  `root` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'the unique id of the root reference spectrum data for current cluster tree node',
  `hash_index` CHAR(32) NOT NULL COMMENT 'the md5 hash key of the tree pathfor search a specific tree node quickly',
  `depth` INT UNSIGNED NOT NULL DEFAULT '1' COMMENT 'the tree path depth of current cluster node',
  `consensus` VARCHAR(4096) NULL DEFAULT '*',
  `annotations` MEDIUMTEXT NULL DEFAULT NULL COMMENT 'the annotation of the current spectrum cluster data',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `spectrum_index` (`root` ASC) INVISIBLE,
  INDEX `parent_node` (`parent_id` ASC) INVISIBLE,
  INDEX `hash_key` (`hash_index` ASC) INVISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE,
  INDEX `cluster_index` (`hash_index` ASC, `model_id` ASC) VISIBLE,
  INDEX `spectrum_size_index` (`n_spectrum` ASC) INVISIBLE,
  INDEX `child_size_index` (`n_childs` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cluster_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cluster_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cluster_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cluster_id` INT UNSIGNED NOT NULL COMMENT 'the cluster tree node id, this id could be duplicated, this data field indicates that which cluster is belongs to of current spectram data',
  `model_id` INT UNSIGNED NOT NULL,
  `metadata_id` INT UNSIGNED NOT NULL COMMENT 'the metabolite annotation id of the current spectrum data',
  `spectral_id` INT UNSIGNED NOT NULL COMMENT 'the spectrum data reference id',
  `score` FLOAT NOT NULL DEFAULT '0' COMMENT 'the score value of current spectrum that align with the root spectrum of current cluster',
  `n_hits` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'number of the ms2 ion fragment hits in the spectrum aignment operation',
  `forward` FLOAT NOT NULL DEFAULT '0',
  `reverse` FLOAT NOT NULL DEFAULT '0',
  `jaccard` FLOAT NOT NULL DEFAULT '0',
  `entropy` FLOAT NOT NULL DEFAULT '0',
  `p_value` DOUBLE NOT NULL DEFAULT '1' COMMENT 't-test p-value of [forward,reverse,jaccard,entropy]',
  `consensus` LONGTEXT NULL DEFAULT NULL COMMENT 'consensus ions m/z value, network byte order data stream in base64 string',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE,
  INDEX `meta_id` (`metadata_id` ASC) VISIBLE,
  INDEX `query_score_item` (`cluster_id` ASC, `spectral_id` ASC) VISIBLE,
  INDEX `find_spectra` (`spectral_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the cluster data link of the spectrum members in current cluster tree node';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cluster_graph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cluster_graph` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cluster_graph` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` INT UNSIGNED NOT NULL,
  `cluster_id` INT UNSIGNED NOT NULL,
  `link_to` INT UNSIGNED NOT NULL,
  `similarity` DOUBLE NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE,
  INDEX `cluster_index1` (`cluster_id` ASC) INVISIBLE,
  INDEX `cluster_index2` (`link_to` ASC) INVISIBLE,
  INDEX `score_index` (`similarity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the networking result based on the cluster table consensus stat result';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cluster_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cluster_tree` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cluster_tree` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cluster_node` INT UNSIGNED NOT NULL COMMENT 'the current cluster tree node id',
  `child_node` INT UNSIGNED NOT NULL COMMENT 'the one of the cluster tree child of current cluster tree node',
  `depth` INT UNSIGNED NOT NULL DEFAULT 0,
  `model_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `cluster_1` (`cluster_node` ASC) INVISIBLE,
  INDEX `cluster_2` (`child_node` ASC) VISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the cluster tree data structrue';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `consensus_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consensus_model` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `consensus_model` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'the parameter id',
  `model_id` INT UNSIGNED NOT NULL,
  `consensus_cutoff` DOUBLE UNSIGNED NOT NULL DEFAULT '0.3' COMMENT 'cutoff value for test two spectrum is identical or not',
  `umap_dimension` INT UNSIGNED NOT NULL DEFAULT '10',
  `umap_neighbors` INT UNSIGNED NOT NULL DEFAULT '15',
  `umap_others` JSON NOT NULL COMMENT 'other umap parameters for create embedding',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `model_info_idx` (`model_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'model and parameters for create consensus analysis result';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `consensus_spectrum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consensus_spectrum` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `consensus_spectrum` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cluster_id` INT UNSIGNED NOT NULL,
  `parameter_id` INT UNSIGNED NOT NULL COMMENT 'parameter id reference of cutoff range and umap parameters',
  `source_size` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'the source cluster size for construct this consensus spectrum. use this parameter for make verify of the cluster data updates(cluster size will change if new spectrum has been added)',
  `precursor` DOUBLE UNSIGNED NOT NULL,
  `precursor_entropy` DOUBLE NOT NULL DEFAULT 0 COMMENT 'entropy of the precursor in this cluster',
  `consensus_entropy` DOUBLE NOT NULL DEFAULT 0 COMMENT 'entropy of the consensus spectrum',
  `splash_id` VARCHAR(45) NOT NULL COMMENT 'splash id of the consensus spectrum',
  `formula` VARCHAR(255) NULL COMMENT 'the highest possible annotated formula of this cluster',
  `adducts` VARCHAR(45) NULL,
  `rt` DOUBLE NULL,
  `mz` LONGTEXT NOT NULL COMMENT 'consensus peak and intensity value, base64strng encoded of double number in network byteorder',
  `intensity` LONGTEXT NOT NULL COMMENT 'consensus peak and intensity value, base64strng encoded of double number in network byteorder',
  `peak_ranking` LONGTEXT NOT NULL COMMENT 'consensus peak annotation and ranking value, base64 string encoded double numbers in network byteorder',
  `umap` VARCHAR(2048) NOT NULL COMMENT 'base64string for umap result of multiple dimension number encoded in network byte order',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `cluster_info_idx` (`cluster_id` ASC) VISIBLE,
  INDEX `parameter_info_idx` (`parameter_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the spectrum data that extract from a cluster data';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `graph_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graph_model` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `graph_model` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'the molecule networking model reference id',
  `name` VARCHAR(255) NOT NULL COMMENT 'the model name',
  `parameters` JSON NOT NULL COMMENT 'json string for the model parameters',
  `description` TEXT NULL DEFAULT NULL,
  `flag` INT NOT NULL DEFAULT '0' COMMENT 'delete flag',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  FULLTEXT INDEX `search_text` (`name`, `description`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the spectrum cluster graph model of the rawdata';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metadata` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `metadata` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hashcode` VARCHAR(32) NOT NULL,
  `mz` DOUBLE NOT NULL DEFAULT '-1' COMMENT 'ms2 spectrum its precursor m/z',
  `rt` DOUBLE NOT NULL DEFAULT '0' COMMENT 'rt of this ms2 spectrum, in time data unit seconds',
  `intensity` DOUBLE NOT NULL DEFAULT '0' COMMENT 'intensity of the ms2 spectrum precursor',
  `filename` VARCHAR(255) NOT NULL,
  `cluster_id` INT UNSIGNED NOT NULL,
  `rawfile` INT UNSIGNED NOT NULL COMMENT 'the raw data file reference id',
  `spectral_id` INT UNSIGNED NOT NULL,
  `model_id` INT UNSIGNED NOT NULL,
  `project_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `project` VARCHAR(255) NOT NULL DEFAULT 'NA',
  `biosample` VARCHAR(64) NOT NULL,
  `organism` VARCHAR(128) NOT NULL,
  `xref_id` VARCHAR(255) NOT NULL COMMENT 'the metabolite annotation reference id to the external metabolite informatyion database, example as biodeep_000000001  or unknown conserved',
  `name` VARCHAR(4096) NOT NULL COMMENT 'the metabolite name',
  `formula` VARCHAR(64) NOT NULL COMMENT 'formula string of the this metabolite, empty for unknown conserved',
  `adducts` VARCHAR(32) NOT NULL COMMENT 'adducts of the metabolite annotation',
  `instrument` VARCHAR(255) NOT NULL DEFAULT 'Thermo Scientific Q Exactive' COMMENT 'instrument name of the raw data file where it generates',
  `add_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idmetadata_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `project_index` (`project_id` ASC) INVISIBLE,
  INDEX `project_index2` (`project` ASC) INVISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE,
  INDEX `metadata_query` (`hashcode` ASC, `cluster_id` ASC, `model_id` ASC) INVISIBLE,
  INDEX `check_duplicated` (`hashcode` ASC, `filename` ASC, `cluster_id` ASC, `model_id` ASC, `project` ASC, `xref_id` ASC) VISIBLE,
  INDEX `biosample_stats` (`organism` ASC, `biosample` ASC) INVISIBLE,
  INDEX `cluster_reference_index` (`cluster_id` ASC) VISIBLE,
  INDEX `metadata_query_index` (`id` ASC, `model_id` ASC, `cluster_id` ASC) VISIBLE,
  INDEX `mass_index` (`mz` ASC) VISIBLE,
  INDEX `time_index` (`rt` ASC) VISIBLE,
  INDEX `spectrum_reference_idx` (`spectral_id` ASC) VISIBLE,
  INDEX `file_source_idx` (`rawfile` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` VARCHAR(128) NOT NULL COMMENT 'the unique identifier of this project in character mode',
  `project_name` VARCHAR(1024) NOT NULL COMMENT 'the project display name',
  `sample_groups` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'number of the sample groups of the samples files in this project',
  `sample_files` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'number of the sample files in current project',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`, `project_id`),
  UNIQUE INDEX `idproject_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `search_id` (`project_id` ASC) VISIBLE,
  FULLTEXT INDEX `search_name` (`project_name`, `note`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the sample file rawdata source note';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rawfiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rawfiles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rawfiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(256) NOT NULL COMMENT 'the sample file name',
  `size_bytes` DOUBLE UNSIGNED NOT NULL DEFAULT '0' COMMENT 'file size in bytes',
  `project_id` INT UNSIGNED NOT NULL,
  `sample_group` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `project_source_idx` (`project_id` ASC) VISIBLE,
  INDEX `group_source_idx` (`sample_group` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sample_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sample_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sample_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(255) NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `sample_files` INT UNSIGNED NOT NULL DEFAULT '0',
  `organism` VARCHAR(255) NOT NULL,
  `bio_samples` VARCHAR(255) NOT NULL,
  `repo_path` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  FULLTEXT INDEX `search_sample_info` (`group_name`, `organism`, `bio_samples`) VISIBLE,
  INDEX `project_info_idx` (`project_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `spectrum_pool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spectrum_pool` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `spectrum_pool` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `npeaks` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'number of ion peaks in current spectrum data',
  `entropy` DOUBLE NOT NULL DEFAULT '0',
  `splash_id` VARCHAR(45) NOT NULL,
  `hashcode` CHAR(32) NOT NULL COMMENT 'md5 hash code of the spectrum data',
  `model_id` INT UNSIGNED NOT NULL,
  `mz` LONGTEXT NOT NULL COMMENT 'mz double array data in network byte order and base64 encoding, andalso the byte data is compress in gzip',
  `into` LONGTEXT NOT NULL COMMENT 'intensity double array data in network byte order and base64 encoding, andalso the byte data is compress in gzip',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `model_index` (`model_id` ASC) VISIBLE,
  INDEX `peak_hash_index` (`hashcode` ASC) VISIBLE,
  INDEX `find_spectrum1` (`id` ASC, `model_id` ASC) VISIBLE,
  INDEX `find_spectrum2` (`hashcode` ASC, `model_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'the spectrum data pool';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
